# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Auditor
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: AuditorMSP

        # ID to load the MSP definition as
        ID: AuditorMSP

        MSPDir: ../organizations/peerOrganizations/auditor.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('AuditorMSP.admin', 'AuditorMSP.peer', 'AuditorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('AuditorMSP.admin', 'AuditorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('AuditorMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('AuditorMSP.peer')"
