# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &FullPackageSupplier
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: FullPackageSupplierMSP

        # ID to load the MSP definition as
        ID: FullPackageSupplierMSP

        MSPDir: ../organizations/peerOrganizations/fullpackagesupplier.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('FullPackageSupplierMSP.admin', 'FullPackageSupplierMSP.peer', 'FullPackageSupplierMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('FullPackageSupplierMSP.admin', 'FullPackageSupplierMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('FullPackageSupplierMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('FullPackageSupplierMSP.peer')"
